// List of all available songs - automatically updated when new songs are added
const availableSongs = [
    "Iktara Wake Up Sid 128 Kbps.mp3",
    "aafreen_aafreen_unplug.mp3",
    "akhiyan_gulab2.mp3",
    "all_of_me.mp3",
    "apna_bana_le.mp3",
    "atif_aslam_new.mp3",
    "dil_diyan_gallan.mp3",
    "dil_song_ringtone.mp3",
    "dil_tu_jaan.mp3",
    "ek_din_teri_raho_me.mp3",
    "falak_tak.mp3",
    "gerua_reverb.mp3",
    "girl_i_need_you.mp3",
    "ha_ham_badalna_laga.mp3",
    "hua_mai_x_finding_her.mp3",
    "ishq_bulaava_bollywood.mp3",
    "jab_jab_tere_pass.mp3",
    "jana_samjho_na.mp3",
    "khairiyat_puchho.mp3",
    "kon_tujhe_peyar_kare.mp3",
    "lut_gaya.mp3",
    "main_shaas_bhi_lu.mp3",
    "malang_sajna.mp3",
    "man_mera.mp3",
    "mehram_animal_2023.mp3",
    "old-town-girl.mp3",
    "paniyon_sa.mp3",
    "queen_bites_dust.mp3",
    "ride_it_hindi.mp3",
    "sahiba_aditya_r.mp3",
    "saiyara.mp3",
    "shaggy_angel.mp3",
    "someone_you_loved.mp3",
    "teddy.mp3",
    "tera_ban_jaunga.mp3",
    "tere_hawaale_arijit.mp3",
    "tere_liye_remix_prin.mp3",
    "teri_ban_jaungi.mp3",
    "thinking_out_loud.mp3",
    "todhi_jagah_marjava.mp3",
    "tu_hain_toh_main_hoon.mp3",
    "tu_hi_yaar_mera.mp3",
    "tuhi_haqeeqat.mp3",
    "tujhe_kitna_chahne.mp3",
    "tum_hi_aana.mp3",
    "tum_jo_aaye.mp3"
];

// Export the songs list
if (typeof module !== 'undefined' && module.exports) {
    module.exports = availableSongs;
}
